### ISSUE TITLE
xp erroring on server

### ISSUE THREAD

**Issue by superon** [Hephaestus-Dev/TinyTweaks#42] opened 2020-12-17 23:30 UTC
receiving the following error spamming the console when removing items the give xp from furnaces etc (items like iron ingots)
https://pastebin.com/DVThrQQ6
changing the easyXp option to true or false doesn't prevent the spam.
also, the upshot is mechanically if i wish to have xp behave normally for mobs (easyXp=false) the xp stays in furnaces until the furnace is broken.
tinytweaks-1.1.2.jar
modlist (taken from console log)
https://pastebin.com/mUbF3jAq
happened as long as i can remember and through at least the last 7 fabric-api updates

**Comment by Burn1ngShad0w** [comment] 2020-12-18 00:11
Have the same Problem and was considering to uninstall tinytweaks as I suspected it being the cause of this behavior. But now I now at least I can get the xp when breaking the furnace. Still would be nice to be addressed in the next version...

**Comment by Haven-King** [comment] 2020-12-18 00:16
I will try to get out a fix for this this weekend.

**Comment by Burn1ngShad0w** [comment] 2020-12-20 17:03
Until it's fixed you can just declare it a "feature" ;)

**Comment by BrekiTomasson** [comment] 2021-01-04 09:27
Any news on this?

**Comment by superon** [comment] 2021-01-15 01:48
> Until it's fixed you can just declare it a "feature" ;)

console spam feature :/

**Comment by superon** [comment] 2021-01-15 01:50
> I will try to get out a fix for this this weekend.

feeling i need to ask if it could be this one :) hope you're well of course

**Comment by Haven-King** [comment] 2021-02-09 17:16
I've fixed this locally, hope to have the update out on CurseForge by the end of the day.

**Comment by superon** [comment] 2021-02-09 23:22
\o/

**Comment by Haven-King** [comment] 2021-02-10 01:26
Fixed in [1.2.0](https://www.curseforge.com/minecraft/mc-mods/tinytweaks/files/3198708).

**Closed as completed by Haven-King** 2021-02-10 01:26 UTC
Labels: bug
